hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
google_login:
    pattern: /login/check-google
logout:
    path:   /logout
nfq_akademija_ads:
    resource: "@NfqAkademijaAdsBundle/Resources/config/routing.yml"
    prefix:   /

