security:
    acl:
        connection: default
    encoders:
        NfqAkademija\AdsBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    providers:
        my_custom_hwi_provider:
            id: ib_user.oauth_user_provider
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            logout: true
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: ib_user.oauth_user_provider
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/user, roles: ROLE_USER }
