<?php

namespace NfqAkademija\AdsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampgainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampgainRepository extends EntityRepository
{
}