<?php

namespace NfqAkademija\AdsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignRepository extends EntityRepository
{
	public function findAllByUser($id)
	{
		return $this->getEntityManager()
		       ->createQuery('SELECT r FROM NfqAkademijaAdsBundle:Campaign r
		       WHERE r.user_id = :id')
		       ->setParameters(array('id' => $id))->getResult();
		//return $this->findBy(array('user_id' => $id));
    }
}
